#!/bin/bash

DOTFILES=$HOME/.dotfiles

delete_and_link() {
    ln -s $DOTFILES/configs/$1 $HOME/$2
}

delete_and_link gitconfig .gitconfig
delete_and_link zprofile .zprofile
delete_and_link zshrc .zshrc

