# Setting GO in PATH
export GOPATH=$HOME/Projekte/Go
export PATH=$PATH:$GOPATH/bin
export GO111MODULE=on

# Export JAVA_HOME for all
export JAVA_HOME=$HOME/.asdf/installs/java/zulu-12.0.1/
export LD_LIBRARY_PATH=$JAVA_HOME/lib/:$JAVA_HOME/lib/server:$LD_LIBRARY_PATH

# Set personal R library path and RStudio R version
export R_LIBS_USER=/home/pscheid/.R/packages
export RSTUDIO_WHICH_R=/opt/microsoft/ropen/3.5.3/lib64/R/bin/R

