# zmodload zsh/zprof
# zprof
# Got slow? Try precompiling
# for f in ~/.dotfiles/**/*.zsh(N); do zcompile "$f"; done
# for f in $ZSH/**/*.zsh(N); do zcompile "$f"; done

export SKIP_COMPINIT=true

autoload -Uz compinit
compinit -u -C -d ~/.zcompdump

compinit()  { : }
compaudit() { : }
zrecompile() { : }

# load configs
setopt extendedglob
DOTFILES=$HOME/.dotfiles
for f ($DOTFILES/zsh/**/*.zsh(.N)) source $f
export DOTFILES
