# Reading profile.d
source /etc/profile

# Setting dotfile folder
DOTFILES=$HOME/.dotfiles

# Reading in zsh configuration
for FILE in $DOTFILES/zsh/**/*; do
    [ -f "$FILE" ] && source "$FILE"
done

# Exporting
export DOTFILES


# TEMPORARY:
# Try xdg-open alias
alias open=xdg-open

# TEMPORARY:
# Try kubectl autocomplete
source <(kubectl completion zsh)

# TEMPORARY:
# Try helm autocomplete
source <(helm completion zsh)

